### PR TITLE
Adds flag -keep-completed, to keeps completed jobs around

### PR DESCRIPTION
**Pull request by atombender**
The flag, if set, prevents completed jobs from being reaped until a certain amount of time has passed.

### CODE REVIEW

**Comment by atombender** [comment]
This resolves #6.

**Comment by atombender** [comment]
Added another flag `-ignore-owned`, to keep owned objects around. (`CronJob` has its own reaping system.)

**Comment by sstarcher** [comment]
LGTM @jmccarty3 any comments before I merge it

**Comment by sstarcher** [comment]
@atombender sorry for the long wait.  I just noticed this was still open.

**Pull request merged**
